name: build

on: push
jobs:
  my-job:
    runs-on: self-hosted
    steps:
      - name: my-step
        run: echo "Hello ASCII Cows!"
      - name: get cow 1
        run: curl -sLS https://firecracker.exit.o6s.io
      - name: working-dir
        run: pwd
      - name: list-current-folder
        run: ls -ltrh
      - name: uname
        run: uname -a
      - name: install-kind
        run: go get sigs.k8s.io/kind
      - name: spin-up-k8s
        run: kind create cluster
