name: build

on: push
jobs:
  my-job:
    runs-on: self-hosted
    steps:
      - name: my-step
        run: echo "Hello ASCII Cows!"
      - name: get cow 1
        run: curl -sLS https://firecracker.exit.o6s.io
      - name: sleep-60-seconds
        run: sleep 60
      - name: list-current-folder
        run: ls -ltrh
      - name: uname
        run: uname -a
